### ISSUE TITLE
[ MVP ROADMAP CHECKLIST ] 

### ISSUE THREAD

**Issue by mvdnet** [occi-cad/occi-server#2]
- [x] Clear modeling, typing and input checking with Pydantic
- [x] Param variants: endpoint query parameter, parameter loading
- [x] Scripts library loading from disk and json file
- [x] Converting script to REST API endpoints with basic input validation
- [x] Basic infrastructure /w docker and docker-compose 
- [x] Scalable worker infrastructure with RMQ (queuing) and Reddis (results)
- [x] Compute async submit: If result is fast return directly, otherwise redirect to compute status URL
- [x] Basic CQ worker (trusted code only) and outputs based on CQGI
- [x] Basic AY worker (trusted code only) and outputs 
- [x] Slow compute flow
- [x] Cache basics:  check, serve, write and manage
- [x] Cache pre-calculation (where possible in scripts) 
- [x] List and search endpoints on library
- [x] Deploy API on public domain for creation of plugin

To research:
- [ ] Combine swagger.json with static parts

Nice to have:

- [ ] thumbnails (SVG?)
- [ ] script requests stats

Dev nice to have:
- [x] ~~Rewrite library directory parsing with pathlib.Path and some clean templates configuration of accepted directory structures~~ (Introduced a simple and strict new namespace structure based on spec)
- [x] For readability in browser with [GET] methods: redirect to default param values. The user can than easily see the params and change values
