### ISSUE TITLE
[ OCCI BASIC ADMIN ] Goals and milestones

### ISSUE THREAD

**Issue by mvdnet** [occi-cad/occi-server#22]
I want to introduce automated publication to a OCCI server. This includes the following functionality:

- [x] Very basic authentication: use a pre-defined passphrase and protect the admin endpoints with it. Use FastAPI HTTP Basic Auth?
- [x] Introduce admin endpoints: /admin/publish, /admin/edit, admin/unpublish for example
- [x] Publication process that might take a long time: pre-calculation and caching, writing to library on disk and a mechanism to follow this publication process by the API user
- [x] #27

Also needed:
- [ ] Don't let publication pre-calculation interfere with real-time requests from API users. Introduce priority in compute tasks
